
[versions]
advrecyclerview = "1.0.0"
androidGradlePlugin = "9.0.1"
annotation = "1.9.1"
appcompat = "1.7.1"
bouncescrollview = "1.5-androidx"
cardview = "1.0.0"
constraintlayout = "2.2.1"
coreKtx = "1.17.0"
coroutinesVersion = "1.10.2"
daggerVersion = "2.59.1"
fragmentKtx = "1.8.9"
glide = "4.16.0"
gridlayout = "1.1.0"
gson = "2.13.2"
imagepicker = "2.1"
koinVersion = "3.5.6"
kotlin = "2.2.10"
legacySupportCoreUi = "1.0.0"
library = "1.6.1"
licensesdialog = "2.2.0"
lifecycleVersion = "2.10.0"
loggingInterceptor = "4.12.0"
material = "1.13.0"
materialDialogVersion = "3.3.0"
media = "1.7.1"
navigation = "2.9.6"
foojay = "0.8.0"
navVersion = "2.9.7"
orgEclipseEgitGithubCore = "2.1.5"
paletteKtx = "1.0.0"
percentlayout = "1.0.0"
preferenceKtx = "1.2.1"
recyclerview = "1.4.0"
retrofit = "2.9.0"
roomVersion = "2.8.4"
utilcodex = "1.31.1"
verticalseekbar = "1.0.0"

[libraries]
adapter-rxjava2 = { module = "com.squareup.retrofit2:adapter-rxjava2", version.ref = "retrofit" }
advrecyclerview = { module = "com.h6ah4i.android.widget.advrecyclerview:advrecyclerview", version.ref = "advrecyclerview" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-gridlayout = { module = "androidx.gridlayout:gridlayout", version.ref = "gridlayout" }
androidx-legacy-support-core-ui = { module = "androidx.legacy:legacy-support-core-ui", version.ref = "legacySupportCoreUi" }
androidx-lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycleVersion" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleVersion" }
androidx-lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "lifecycleVersion" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleVersion" }
androidx-media = { module = "androidx.media:media", version.ref = "media" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navVersion" }
androidx-navigation-runtime-ktx = { module = "androidx.navigation:navigation-runtime-ktx", version.ref = "navVersion" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navVersion" }
androidx-palette-ktx = { module = "androidx.palette:palette-ktx", version.ref = "paletteKtx" }
androidx-percentlayout = { module = "androidx.percentlayout:percentlayout", version.ref = "percentlayout" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomVersion" }
androidx-room-guava = { module = "androidx.room:room-guava", version.ref = "roomVersion" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomVersion" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomVersion" }
androidx-room-rxjava2 = { module = "androidx.room:room-rxjava2", version.ref = "roomVersion" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "roomVersion" }
bottomsheets = { module = "com.afollestad.material-dialogs:bottomsheets", version.ref = "materialDialogVersion" }
bouncescrollview = { module = "com.github.woxingxiao:BounceScrollView", version.ref = "bouncescrollview" }
color = { module = "com.afollestad.material-dialogs:color", version.ref = "materialDialogVersion" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
core = { module = "com.afollestad.material-dialogs:core", version.ref = "materialDialogVersion" }
dagger = { module = "com.google.dagger:dagger", version.ref = "daggerVersion" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "daggerVersion" }
datetime = { module = "com.afollestad.material-dialogs:datetime", version.ref = "materialDialogVersion" }
files = { module = "com.afollestad.material-dialogs:files", version.ref = "materialDialogVersion" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
imagepicker = { module = "com.github.dhaval2404:imagepicker", version.ref = "imagepicker" }
input = { module = "com.afollestad.material-dialogs:input", version.ref = "materialDialogVersion" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinVersion" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutinesVersion" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutinesVersion" }
library = { module = "me.zhanghai.android.materialprogressbar:library", version.ref = "library" }
licensesdialog = { module = "de.psdev.licensesdialog:licensesdialog", version.ref = "licensesdialog" }
lifecycle = { module = "com.afollestad.material-dialogs:lifecycle", version.ref = "materialDialogVersion" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
material = { module = "com.google.android.material:material", version.ref = "material" }
okhttp3-integration = { module = "com.github.bumptech.glide:okhttp3-integration", version.ref = "glide" }
org-eclipse-egit-github-core = { module = "org.eclipse.mylyn.github:org.eclipse.egit.github.core", version.ref = "orgEclipseEgitGithubCore" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
utilcodex = { module = "com.blankj:utilcodex", version.ref = "utilcodex" }
verticalseekbar = { module = "com.h6ah4i.android.widget.verticalseekbar:verticalseekbar", version.ref = "verticalseekbar" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
navigation-safeArgs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation" }
foojay-resolver = { id = "org.gradle.toolchains.foojay-resolver-convention", version.ref = "foojay" }
